@echo off
REM pre-commit hook — clang-tidy static analysis on staged .cpp/.hpp files in Src/
REM
REM Install:  git config core.hooksPath githooks
REM
REM Prerequisites:
REM   - compile_commands.json in project root (generated by "generate-compile-commands.cmd")
REM   - Clang 18 at C:\Program Files\clang+llvm-18.1.8-x86_64-pc-windows-msvc
REM   - VS 2022 v17 toolchain at E:\Program Files\Microsoft Visual Studio\2022\Community

setlocal enabledelayedexpansion

set "TIDY=C:\Program Files\clang+llvm-18.1.8-x86_64-pc-windows-msvc\bin\clang-tidy.exe"
set "VC_INSTALL=E:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.29.30133"
set "COMPDB=%CD%\compile_commands.json"

if not exist "%TIDY%" (
    echo [pre-commit] ERROR: clang-tidy not found at %TIDY%
    exit /b 1
)

if not exist "%COMPDB%" (
    echo [pre-commit] ERROR: compile_commands.json not found.
    echo [pre-commit] Run generate-compile-commands.cmd first.
    exit /b 1
)

set "HAS_ERRORS=0"

for /f "usebackq tokens=*" %%f in (`git diff --cached --name-only --diff-filter=ACM`) do (
    set "IS_SRC=0"
    echo %%f | findstr /r "^Src\\..*\.\(cpp\|hpp\)$" >nul && set "IS_SRC=1"
    if not "%%f"=="" (
        echo %%f | findstr /r /i "^Src\\.*\.\(cpp\|hpp\)$" >nul
        if not errorlevel 1 (
            echo [pre-commit] checking %%f ...
            set "FULLPATH=%CD%\%%f"
            set "VCToolsInstallDir=%VC_INSTALL%"
            "%TIDY%" -p "%CD%" --quiet --header-filter="Src/" "%%f" 2>&1 | findstr /r /c:"error:" >nul
            if not errorlevel 1 (
                echo [pre-commit] ERROR: clang-tidy found issues in %%f
                set "HAS_ERRORS=1"
            ) else (
                "%TIDY%" -p "%CD%" --quiet --header-filter="Src/" "%%f" 2>&1 | findstr /r /c:"warning: Src/" >nul
                if not errorlevel 1 (
                    echo [pre-commit] WARNING: clang-tidy warnings in %%f
                )
            )
        )
    )
)

if "%HAS_ERRORS%"=="1" (
    echo [pre-commit] Commit blocked. Fix the errors above and try again.
    exit /b 1
)

exit /b 0
